blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='posts'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail')
]

breeding/urls.py
from django.urls import path
from . import views


app_name = 'breeding'


urlpatterns = [
    path('our-dogs/', views.our_dogs, name='our_dogs'),
    path('our-dogs/<int:breed_id>/', views.our_dogs, name='our_dogs'),
    
    path('buy-a-dog/', views.buy_a_dog, name='buy_a_dog'),
    path('buy-a-dog/<int:dog_id>/', views.dog_detail, name='dog_detail'),
    path('buy-a-dog/<int:dog_id>/pre_reserve', views.pre_reserve_dog, name='pre_reserve_dog'),
    
    path('upcoming-litters/', views.upcoming_litters, name='upcoming_litters'),
    path('upcoming-litters/<int:litter_id>/', views.litter_detail, name='litter_detail'),
    path('upcoming-litters/<int:dog_id>/pre_reserve', views.pre_reserve_litter, name='pre_reserve_litter'),
]

fortissimusbellator/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


from fortissimusbellator import admin
from .views import FileUploadView, EditorJsImageUploadByFileView, EditorJsImageUploadByUrlView

urlpatterns = [
    # path('i18n/', include('django.conf.urls.i18n')),
    path('upload/', FileUploadView.as_view(), name='upload'),
    path('editorjs/image/upload/file/', EditorJsImageUploadByFileView.as_view(), name='editorjs_image_upload_by_file'),
    path('editorjs/image/upload/url/', EditorJsImageUploadByUrlView.as_view(), name='editorjs_image_upload_by_url'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('frontoffice.urls')),
    path('', include('breeding.urls')),
    path('', include('accounts.urls')),
    path('quiz/', include('quiz.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),

    prefix_default_language=True
)

frontoffice/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about-us/', views.about_us, name='about_us'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('faqs/', views.faqs, name='faqs'),
]

frontoffice/models.py
import pathlib
import mimetypes

from uuid import uuid4

from django.db import models
from django.utils.translation import gettext_lazy as _


def faq_image_upload_to(instance: 'FrequentlyAskedQuestion', filename: str) -> str:
    extension = mimetypes.guess_extension(filename)

    if not extension:
        extension = pathlib.Path(filename).suffix

    return f"faqs/{uuid4().hex}{extension}"


class FrequentlyAskedQuestion(models.Model):
    question = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        verbose_name=_('question')
    )

    answer = models.TextField(
        null=False,
        blank=False,
        verbose_name=_('answer')
    )

    image = models.ImageField(
        upload_to=faq_image_upload_to,
        null=True,
        blank=True,
        verbose_name=_('image'),
    )

    active = models.BooleanField(
        default=True,
        verbose_name=_('active')
    )

    order = models.IntegerField(
        default=999,
        verbose_name=_('order'),
    )

    class Meta:
        verbose_name = _('Frequently Asked Question')
        verbose_name_plural = _('Frequently Asked Questions')
        ordering = ['order']

    def __str__(self):
        return f"{self.question}"

frontoffice/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'placeholder': _('Your Name')
            }
        )
    )

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': _('Your Email')
            }
        )
    )

    phone = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                'placeholder': _('Your Email')
            }
        )
    )

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': _('Your Message'),
                'rows': 5
            }
        )
    )

    captcha = ReCaptchaField(
        widget=ReCaptchaV3()
    )

frontoffice/views.py
from smtplib import SMTPException

from django.utils.translation import gettext_lazy as _
from django.shortcuts import render, redirect
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib import messages
from django.template.loader import render_to_string

from attachments.models import Attachment
from .models import FrequentlyAskedQuestion
from .forms import ContactForm


def home(request):
    return render(request, 'home/index.html')


def about_us(request):
    gallery = Attachment.objects.filter(mime_type__startswith='image').order_by('?')[:50]
    return render(request, 'about_us.html', { 'gallery': gallery })


def faqs(request):
    faqs = FrequentlyAskedQuestion.objects.filter(active=True).order_by('order')
    return render(request, 'faqs.html', {'faqs': faqs})


def send_contact_email(form):
    name = form.cleaned_data['name']
    email = form.cleaned_data['email']
    phone = form.cleaned_data['phone']
    message = form.cleaned_data['message']

    html_message = render_to_string(
        'emails/contact_us.html',
        {
            'name': name,
            'email': email,
            'phone': phone,
            'message': message,
        }
    )

    email = EmailMessage(
        subject=_(f"Contact Form Submission from {name}"),
        body=html_message,
        from_email=settings.DEFAULT_FROM_EMAIL,
        to=settings.RECIPIENT_LIST_ON_CONTACT_US_REQUEST,
    )

    email.content_subtype = "html"
    email.send(fail_silently=False)


def contact_us(request):
    if request.method != 'POST':
        return render(request, 'contact_us.html', {'form': ContactForm()})

    form = ContactForm(request.POST)

    if not form.is_valid():
        messages.error(request, _('Please fill out all fields.'))
        return render(request, 'contact_us.html', {'form': form})

    try:
        send_contact_email(form)
        messages.success(request, _('Thank you! We will get back to you soon.'))
    except SMTPException as e:
        print("Error sending email:", e)
        messages.error(request, _('Ups... Try again later.'))

    return redirect('contact_us')

frontoffice/templates/home/_card_breed.html
{% load i18n %}

<div class="bg-white dark:bg-stone-900 rounded-lg shadow-lg transform hover:scale-105 transition duration-300 overflow-hidden">
    {% if breed.cover %}
    <img src="{{ breed.cover.url }}" alt="{{ breed.name_en }} puppy from a breeder in Portugal" class="w-full h-64 object-cover rounded-t-lg" loading="lazy">
    {% endif %}
    <div class="p-6">
        <h3 class="font-serif text-2xl font-bold text-stone-900 dark:text-white">
            {{ breed }}
        </h3>
        <p class="font-sans text-stone-700 dark:text-stone-300 mt-4 leading-relaxed">
            {{ breed.description }}
        </p>
        <a href="{% url 'breeding:buy_a_dog' %}?breed={{ breed.pk }}"
           class="mt-6 inline-block bg-stone-700 text-white px-6 py-3 rounded-full hover:bg-stone-600 transition duration-300 font-sans shadow-lg"
           aria-label="{% blocktrans with breed_name=breed.name %}Learn more about the breed {{ breed_name }}{% endblocktrans %}">
            {% translate "Learn More" %}
        </a>
    </div>
</div>

frontoffice/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load fortissimus_bellator %}

{% block content %}
    <!-- Hero Section -->
    <div class="bg-cover bg-center h-screen relative" style="background-image: url({% static 'imgs/home.webp' %});" fetchpriority="high">
        <!-- Gradient Overlay -->
        <div class="absolute inset-0 bg-gradient-to-b from-black/90 via-black/40 to-transparent"></div>
    
        <!-- Content Wrapper -->
        <div class="flex items-end justify-center h-full relative pb-20 lg:pb-24">
            <div class="text-center text-white px-6">
                <!-- Text Container -->
                <div class="backdrop-blur-sm bg-black/30 p-8 md:p-12 rounded-xl shadow-lg">
                    <!-- Heading -->
                    <h1 class="text-lg sm:text-xl md:text-2xl lg:text-3xl xl:text-4xl font-metamorphous font-bold drop-shadow-lg tracking-wide">
                        Fortissimus Bellator
                    </h1>
                    <!-- Subtitle -->
                    <p class="text-xs sm:text-sm md:text-base lg:text-lg xl:text-xl pt-4 mt-2 md:mt-4 max-w-md md:max-w-lg lg:max-w-2xl xl:max-w-5xl mx-auto leading-relaxed tracking-wide">
                        {% translate "Dedicated to breeding strong, intelligent, and well-socialized dogs. Our passion ensures that each breed maintains its unique characteristics and health." %}
                    </p>
                </div>
            </div>
        </div>
    </div>
    
    <!-- About Our Breeding Philosophy -->
    <div class="mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h2 class="font-serif text-3xl font-bold text-center text-stone-900 dark:text-white">
            {% translate "Our Philosophy" %}
        </h2>
        <p class="font-sans text-center text-stone-700 dark:text-stone-300 mt-4 max-w-3xl mx-auto leading-relaxed">
            {% translate "At Fortissimus Bellator, we believe in ethical breeding practices. Our dogs grow in a healthy, loving environment, focusing on temperament, intelligence, and physical ability to produce exceptional companions." %}
        </p>
    </div>

    <!-- Featured Breeds Section -->
    <div class="px-4 sm:px-6 lg:px-8 py-16 bg-stone-100 dark:bg-stone-800">
        <div class="mx-auto max-w-7xl">
            <h2 class="font-serif text-3xl font-bold text-center text-stone-900 dark:text-white">
                {% translate "Our Breeds" %}
            </h2>
            <p class="font-sans text-center text-stone-700 dark:text-stone-300 mt-4 max-w-3xl mx-auto leading-relaxed">
                {% translate "Each of our breeds is carefully selected and raised with dedication to ensure they become well-balanced companions in loving homes." %}
            </p>
            <div class="mt-12 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {% for breed in featured_breeds %}
                    {% include "home/_card_breed.html" with breed=breed %}
                {% endfor %}
            </div>
        </div>
    </div>

    {% include "components/parallax.html" with image='imgs/dog_play.jpg'|static_url %}

    <!-- Responsible Ownership Section -->
    <div class="mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h2 class="font-serif text-3xl font-bold text-stone-900 dark:text-white">
                {% translate "Responsible Ownership" %}
            </h2>
            <p class="font-sans text-stone-700 dark:text-stone-300 mt-4 max-w-3xl mx-auto leading-relaxed">
                {% translate "Owning a dog is a lifelong commitment. We guide future owners on training, nutrition, and care to ensure our dogs find the best homes." %}
            </p>
        </div>
        <div class="p-10">
            {% include "components/quiz_cta.html" %}
        </div>
    </div>
{% endblock %}